### ISSUE TITLE
`docker-compose --project-name=ocean up` fails

### ISSUE THREAD

**Issue by H34D** [oceanprotocol/docker-images#29]
## Expected Behavior

If i run

```bash
export OCEAN_VERSION=latest
docker-compose --project-name=ocean up
```

from https://github.com/oceanprotocol/docker-images/blob/develop/README.md
it should spin up ocean's default env. This leads to an error now. I think there is something missing in the documentation?

## Current Behavior

```bash
Creating ocean_keeper-contracts_1 ... error
Creating ocean_mongodb_1          ... 

ERROR: for ocean_keeper-contracts_1  Cannot create container for service keeper-contracts: create .: volume name is too short, names should be at least two alphCreating ocean_mongodb_1          ... done

ERROR: for keeper-contracts  Cannot create container for service keeper-contracts: create .: volume name is too short, names should be at least two alphanumeric characters
ERROR: Encountered errors while bringing up the project.
```

**Comment by kremalicious** [comment]
can confirm. The updated `docker-compose.yml` now requires a bunch of environment variables which are only set by using the new `start_ocean.sh` script. So guess would make sense to default to the script and extending it a bit more, instead of trying to figure out how to support the script and the raw commands. For that we should change script a bit:

- default to `stable` versions of all components
- make `latest` versions configurable with argument, e.g. `--latest`

Right now, the script can be used to get the latest versions of everything so it's essentially the same outcome as the currently documented commands to get latest of everything 

I can look into that, currently in testing mode with all this, and in combination with `pleuston`

**Comment by kremalicious** [comment]
I removed the `docker-compose` commands from the readme in here so at least community doesn't run into this issue https://github.com/oceanprotocol/docker-images/pull/32

Don't know if it's worth trying to make everything work with no environment variables set and the raw `docker-compose` command

**Comment by jcortejoso** [comment]
It should be fixed.
